In [1]:
import pandas as pd

In [2]:
# load csv file
data = pd.read_excel("car data.xlsx")

In [3]:
data

      Index Buying  Maint  Doors Persons Lug boot Safety  Class
0         0  vhigh  vhigh      2       2    small    low  unacc
1         1  vhigh  vhigh      2       2    small    med  unacc
2         2  vhigh  vhigh      2       2    small   high  unacc
3         3  vhigh  vhigh      2       2      med    low  unacc
4         4  vhigh  vhigh      2       2      med    med  unacc
5         5  vhigh  vhigh      2       2      med   high  unacc
6         6  vhigh  vhigh      2       2      big    low  unacc
7         7  vhigh  vhigh      2       2      big    med  unacc
8         8  vhigh  vhigh      2       2      big   high  unacc
9         9  vhigh  vhigh      2       4    small    low  unacc
10       10  vhigh  vhigh      2       4    small    med  unacc
11       11  vhigh  vhigh      2       4    small   high  unacc
12       12  vhigh  vhigh      2       4      med    low  unacc
13       13  vhigh  vhigh      2       4      med    med  unacc
14       14  vhigh  vhigh      2       4      med   high  unacc
15       15  vhigh  vhigh      2       4      big    low  unacc
16       16  vhigh  vhigh      2       4      big    med  unacc
17       17  vhigh  vhigh      2       4      big   high  unacc
18       18  vhigh  vhigh      2    more    small    low  unacc
19       19  vhigh  vhigh      2    more    small    med  unacc
20       20  vhigh  vhigh      2    more    small   high  unacc
21       21  vhigh  vhigh      2    more      med    low  unacc
22       22  vhigh  vhigh      2    more      med    med  unacc
23       23  vhigh  vhigh      2    more      med   high  unacc
24       24  vhigh  vhigh      2    more      big    low  unacc
25       25  vhigh  vhigh      2    more      big    med  unacc
26       26  vhigh  vhigh      2    more      big   high  unacc
27       27  vhigh  vhigh      3       2    small    low  unacc
28       28  vhigh  vhigh      3       2    small    med  unacc
29       29  vhigh  vhigh      3       2    small   high  unacc
...     ...    ...    ...    ...     ...      ...    ...    ...
1698   1698    low    low      4    more      big    low  unacc
1699   1699    low    low      4    more      big    med   good
1700   1700    low    low      4    more      big   high  vgood
1701   1701    low    low  5more       2    small    low  unacc
1702   1702    low    low  5more       2    small    med  unacc
1703   1703    low    low  5more       2    small   high  unacc
1704   1704    low    low  5more       2      med    low  unacc
1705   1705    low    low  5more       2      med    med  unacc
1706   1706    low    low  5more       2      med   high  unacc
1707   1707    low    low  5more       2      big    low  unacc
1708   1708    low    low  5more       2      big    med  unacc
1709   1709    low    low  5more       2      big   high  unacc
1710   1710    low    low  5more       4    small    low  unacc
1711   1711    low    low  5more       4    small    med    acc
1712   1712    low    low  5more       4    small   high   good
1713   1713    low    low  5more       4      med    low  unacc
1714   1714    low    low  5more       4      med    med   good
1715   1715    low    low  5more       4      med   high  vgood
1716   1716    low    low  5more       4      big    low  unacc
1717   1717    low    low  5more       4      big    med   good
1718   1718    low    low  5more       4      big   high  vgood
1719   1719    low    low  5more    more    small    low  unacc
1720   1720    low    low  5more    more    small    med    acc
1721   1721    low    low  5more    more    small   high   good
1722   1722    low    low  5more    more      med    low  unacc
1723   1723    low    low  5more    more      med    med   good
1724   1724    low    low  5more    more      med   high  vgood
1725   1725    low    low  5more    more      big    low  unacc
1726   1726    low    low  5more    more      big    med   good
1727   1727    low    low  5more    more      big   high  vgood

[1728 rows x 8 columns]

In [4]:
data.head()

   Index Buying  Maint Doors Persons Lug boot Safety  Class
0      0  vhigh  vhigh     2       2    small    low  unacc
1      1  vhigh  vhigh     2       2    small    med  unacc
2      2  vhigh  vhigh     2       2    small   high  unacc
3      3  vhigh  vhigh     2       2      med    low  unacc
4      4  vhigh  vhigh     2       2      med    med  unacc

In [5]:
data.head(10)

   Index Buying  Maint Doors Persons Lug boot Safety  Class
0      0  vhigh  vhigh     2       2    small    low  unacc
1      1  vhigh  vhigh     2       2    small    med  unacc
2      2  vhigh  vhigh     2       2    small   high  unacc
3      3  vhigh  vhigh     2       2      med    low  unacc
4      4  vhigh  vhigh     2       2      med    med  unacc
5      5  vhigh  vhigh     2       2      med   high  unacc
6      6  vhigh  vhigh     2       2      big    low  unacc
7      7  vhigh  vhigh     2       2      big    med  unacc
8      8  vhigh  vhigh     2       2      big   high  unacc
9      9  vhigh  vhigh     2       4    small    low  unacc

In [6]:
data.groupby("Buying").groups

{'high': Int64Index([432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
             ...
             854, 855, 856, 857, 858, 859, 860, 861, 862, 863],
            dtype='int64', length=432),
 'low': Int64Index([1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305,
             ...
             1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727],
            dtype='int64', length=432),
 'med': Int64Index([ 864,  865,  866,  867,  868,  869,  870,  871,  872,  873,
             ...
             1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295],
            dtype='int64', length=432),
 'vhigh': Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
             ...
             422, 423, 424, 425, 426, 427, 428, 429, 430, 431],
            dtype='int64', length=432)}

In [8]:
data["highprice"] = data["Buying"] == "vhigh"
data.head()

   Index Buying  Maint Doors Persons Lug boot Safety  Class  highprice
0      0  vhigh  vhigh     2       2    small    low  unacc       True
1      1  vhigh  vhigh     2       2    small    med  unacc       True
2      2  vhigh  vhigh     2       2    small   high  unacc       True
3      3  vhigh  vhigh     2       2      med    low  unacc       True
4      4  vhigh  vhigh     2       2      med    med  unacc       True

In [9]:
data.groupby("highprice").groups

{False: Int64Index([ 432,  433,  434,  435,  436,  437,  438,  439,  440,  441,
             ...
             1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727],
            dtype='int64', length=1296),
 True: Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
             ...
             422, 423, 424, 425, 426, 427, 428, 429, 430, 431],
            dtype='int64', length=432)}

In [11]:
data.count()

Index        1728
Buying       1728
Maint        1728
Doors        1728
Persons      1728
Lug boot     1728
Safety       1728
Class        1728
highprice    1728
dtype: int64

In [12]:
data["Buying"].count()

1728

In [13]:
data.Buying.count()

1728

In [15]:
data.groupby("highprice")["highprice"].count()

highprice
False    1296
True      432
Name: highprice, dtype: int64

In [17]:
data.groupby("highprice")["highprice"].count() / data.Buying.count()

highprice
False    0.75
True     0.25
Name: highprice, dtype: float64

In [19]:
data.groupby("Class")["highprice"].value_counts() / data.Buying.count()

Class  highprice
acc    False        0.180556
       True         0.041667
good   False        0.039931
unacc  False        0.491898
       True         0.208333
vgood  False        0.037616
Name: highprice, dtype: float64

In [21]:
data.groupby("Class")["highprice"].value_counts() / data.groupby("Class")["highprice"].count()

Class  highprice
acc    False        0.812500
       True         0.187500
good   False        1.000000
unacc  False        0.702479
       True         0.297521
vgood  False        1.000000
Name: highprice, dtype: float64

In [22]:
# Done